language: ruby
rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_f05b37f4d69b_key -iv $encrypted_f05b37f4d69b_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key -d
- sudo apt-get update
- sudo apt-get install oracle-java8-installer
- sudo update-java-alternatives -s java-8-oracle
before_script:
- pip install --user html5validator
script: ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  on:
    branch: master
