language: ruby
rvm:
- 2.1
before_install:
- sudo apt-get update
- sudo apt-get install oracle-java8-installer
- sudo update-java-alternatives -s java-8-oracle
before_script:
- pip install --user html5validator
script: ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  on:
    branch: master
