# Permalinks
permalink:           pretty

# Setup
title:               Strategic Data
url:                 http://www.strategicdata.com.au

# About/contact
author:
  name:              'Strategic Data'
  email:             'info@strategicdata.com.au'
  github:            'https://github.com/strategicdata/strategicdata.com.au'

exclude: [node_modules,vendor,blog,_posts]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
