# Permalinks
permalink:           pretty

# Setup
title:               Strategic Data
url:                 http://new.strategicdata.com.au/
paginate:            5

# Gems
gems:
  - jekyll-tagging
  - jekyll-paginate

#tag_page_layout: tag_page
#tag_page_dir: tag

exclude: [node_modules,vendor]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
