# Permalinks
permalink:           pretty

# Setup
title:               Strategic Data
url:                 http://new.strategicdata.com.au/

exclude: [node_modules,vendor]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
